name: flask-cleaner

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          python -m pip install flake8
          python -m flake8 .

      - name: Check dependencies for vulnerabilities
        run: |
          python -m pip install safety
          python -m safety check -r requirements.txt

      - name: Security scan with Bandit
        run: |
          python -m pip install bandit
          python -m bandit -r .
          